#!/usr/bin/env python3
# Generates addon/shadow_page.conf - readout/toggle/button/knob/stepper
# widgets take cx/cy (center point), not x/y (top-left); frame/list take
# x/y (top-left). Confirmed against force-shadow/src/force_shadow.c's real
# parser, not just the preview tool. Doing this by hand for 16 pads is
# exactly how the first draft got it wrong.
#
# v4 (2026-09-22): two pages instead of the earlier four-tab design (PADS
# 1-8/9-16, GLOBAL, POOL ASSIGN), based on hand-drawn sketches - see
# DESIGN.md's "v4" section for the full redesign history, what got tried
# and rejected along the way, and the real render-caught bugs (list grid
# overflow, a readout drawn on top of a frame's own title, a padded PLAY
# button bleeding into the next pad's column) that shaped the final
# coordinates below.

HEADER = '''# ForceKitBuilder — shadow-GUI page (v4: two pages - PADS performance
# grid + DETAIL single-pad view). See DESIGN.md's "v4" section for the
# full redesign history.
#
# page=8, not 1-7: only seven SHIFT+SCENE-N combos physically exist, and
# on the real device all seven were already taken (DX7, JV-880, Maze
# Voice, Maze Seq, Acid, Euclidier, plus force-shadow's own launcher at
# slot 7). Kit Builder is exactly the "low-frequency tool" case
# docs/adding-a-page.md's "Add-on launcher (tool add-ons)" section
# describes - page 8+ isn't combo-bound, it's reached via the launcher
# page (SHIFT+SCENE-7) instead.
#
# Colour scheme: an approximation of the Akai Force's own OS look (dark
# charcoal chassis, orange selection/accent, neutral grey buttons) - no
# verified reference screenshot or hex values for the real Force OS
# exist in this repo family yet, treat these as a starting point to
# refine once compared against real hardware. Keeps style=td3's proven
# widget shapes (rounded frames, pill buttons), only the theme_* colour
# values are overridden.
#
# IMPORTANT widget coordinate rule (confirmed against
# force-shadow/src/force_shadow.c's real conf parser, not just the
# preview tool): frame and list take x=/y= (top-left corner). Every
# other widget kind - readout, toggle, button, knob, stepper, enum_h/v -
# takes cx=/cy= (CENTER point). Mixing these up doesn't error, it just
# silently draws at/near (0,0) or on top of a frame's own title text -
# caught by rendering with force-shadow/tools/render_conf_preview before
# deploying, not by inspection, more than once while building this file.
#
# Also confirmed: frame widgets don't count against the real device's
# 64-widget-per-tab cap (force_shadow.c: `if (strcmp(type, "frame") != 0
# && n_page_widgets >= MAX_WIDGETS)`) - per-pad frames on the PADS page
# are free. The preview tool's OWN line-storage buffer is separately
# capped at 64 *lines* per tab including frames though (a tooling
# limitation, not a real constraint) - PADS's 65 conf lines (16 frames +
# 48 controls + 1 topbar readout) means the preview tool silently drops
# pad 16's last line; the real device is unaffected (confirmed no
# equivalent buffer in force_shadow.c's own line-by-line parser).
#
# Button widgets have a FIXED height in this format (48px, td3-style) -
# width grows with label text (padding a label with spaces measurably
# widens it - see PLAY on the DETAIL page below) but there is no w=/h=
# override for buttons in the real conf parser, so a literal bigger
# *square* button isn't achievable. A knob was considered as a tap-to-
# play alternative and ruled out after reading force_shadow.c's touch
# handler: W_KNOB only arms a drag on touch-down, nothing fires on a
# plain tap.
#
# Generated by tools/gen_shadow_page.py (force-kit-builder repo) - edit
# that script and regenerate rather than hand-editing this file.
page=8
ctrl_sock=/tmp/kitbuilder_ctrl.sock
display_name="KIT BUILDER"

style=td3
theme_bg=1a1a1a
theme_panel=1a1a1a
theme_line=2e2e2e
theme_ink=f2f2f2
theme_ink_dim=aaaaaa
theme_ink_faint=666666
theme_accent=ff8f00
theme_accent_hi=ffb74d
theme_knob_face=2a2a2a
theme_knob_ring=000000
theme_bar=2a2a2a
theme_seg_active=ff8f00
theme_seg_inactive=2a2a2a
theme_seg_active_tx=000000
theme_btn_text=ffffff
theme_well=000000
theme_knob_off=444444
theme_tab_on=2a2a2a
theme_lcd=000000
theme_box=202020
theme_btn_bg=3a3a3c
theme_chrome_ink=ffffff
theme_go_on=00e676
theme_go_off=616161
theme_tabs=1a1a1a
'''

ACCENT_HEX = 'ff8f00'   # same hex as theme_accent - button color= override

TOPBAR_LASTPLAYED = 'readout cx=840 cy=36 w=780 h=48 label="" get=status'

# core/sample_index.mjs's ROLE_ORDER, hardcoded here rather than read live -
# this script has no Node runtime to import it with. Keep in sync by hand;
# a mismatch wouldn't error, it would just leave one category untoggleable
# (same class of silent-drift risk shadow-gui.md warns about for engine/
# web/shadow param triples generally).
CATEGORIES = [
    ('kick', 'KICK'), ('snare', 'SNARE'), ('rim', 'RIM'), ('clap', 'CLAP'),
    ('hat', 'HAT'), ('closed_hat', 'CLOSED HAT'), ('open_hat', 'OPEN HAT'),
    ('tom', 'TOM'), ('conga', 'CONGA'), ('percussion', 'PERC'),
    ('crash', 'CRASH'), ('ride', 'RIDE'), ('cymbal', 'CYMBAL'), ('fx', 'FX'),
    ('glitch', 'GLITCH'), ('vox', 'VOX'), ('bass', 'BASS'), ('synth', 'SYNTH'),
    ('stab', 'STAB'), ('chord', 'CHORD'), ('lead', 'LEAD'), ('pad', 'PAD'),
    ('other', 'OTHER'),
]

# ---- PADS page: 16-pad 4x4 performance grid --------------------------------
# 16 pads x 4 controls (LOCK/CLEAR/REROLL/PLAY) would be exactly 64 - zero
# room left for the top-bar "last played" readout this page also needs.
# CLEAR dropped here (kept on DETAIL) rather than the readout -
# LOCK/REROLL/PLAY are the "in the moment" actions, CLEAR fits DETAIL's
# editing role better. 16*3 + 1 = 49, comfortable headroom.
PADS_ROW_Y = [82, 244, 406, 568]
PADS_COL_X = [20, 335, 650, 965]
PADS_CELL_W, PADS_CELL_H = 295, 150


def pads_cell(pad_num, pad_index, x, y):
    # Frames are free (see HEADER's note) - a per-pad box is both the
    # visual contrast asked for and a place to put the pad number, at
    # zero extra widget cost. Left half = PLAY, right half = LOCK over
    # REROLL, stacked. PLAY's label is NOT padded here (unlike DETAIL's
    # wider bar) - a padded "   PLAY   " computes to 208px wide (checked
    # via the renderer's real text_width() formula, not guessed), but
    # this cell's left-half zone is only ~147px - it bled into the
    # neighbouring pad's column in an earlier draft.
    left_cx = x + PADS_CELL_W // 4
    right_cx = x + (PADS_CELL_W * 3) // 4
    mid_cy = y + 92
    lock_cy = y + 68
    reroll_cy = y + 118
    return '\n'.join([
        f'frame   x={x} y={y} w={PADS_CELL_W} h={PADS_CELL_H} title="{pad_num}"',
        f'button  cx={left_cx} cy={mid_cy} label="PLAY" key=play_pad_{pad_index} color={ACCENT_HEX}',
        f'toggle  cx={right_cx} cy={lock_cy} label="LOCK" key=pad_lock_{pad_index}',
        f'button  cx={right_cx} cy={reroll_cy} label="REROLL" key=reroll_pad_{pad_index}',
    ])


def pads_grid_tab():
    lines = ['[tab PADS]', TOPBAR_LASTPLAYED, '']
    for row in range(4):
        for col in range(4):
            pad_index = row * 4 + col
            x, y = PADS_COL_X[col], PADS_ROW_Y[row]
            lines.append(pads_cell(pad_index + 1, pad_index, x, y))
            lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


# ---- DETAIL page ------------------------------------------------------------
# Top-left: category toggle matrix. Top-right: global actions, vertical
# stack. Bottom: full-width pad detail bar (wide readout so the sample
# name truncates less than a narrow column would allow).
CAT_FRAME = (20, 82, 900, 406)
GLOBAL_COL = (940, 82, 300, 406)
DETAIL_BAR = (20, 508, 1240, 220)
CAT_COLS, CAT_ROWS = 6, 4


def detail_tab():
    cfx, cfy, cfw, cfh = CAT_FRAME
    gx, gy, gw, gh = GLOBAL_COL
    dbx, dby, dbw, dbh = DETAIL_BAR
    gcx = gx + gw // 2

    lines = [
        '[tab DETAIL]',
        f'frame   x={cfx} y={cfy} w={cfw} h={cfh} title="CATEGORY - TAP TO TOGGLE"',
    ]

    interior_x0, interior_x1 = cfx + 16, cfx + cfw - 16
    interior_y0, interior_y1 = cfy + 40, cfy + cfh - 16
    col_step = (interior_x1 - interior_x0) / CAT_COLS
    row_step = (interior_y1 - interior_y0) / CAT_ROWS
    for i, (cat, label) in enumerate(CATEGORIES):
        col, row = i % CAT_COLS, i // CAT_COLS
        cx = int(interior_x0 + col_step * col + col_step / 2)
        cy = int(interior_y0 + row_step * row + row_step / 2)
        lines.append(f'toggle  cx={cx} cy={cy} label="{label}" key=detail_cat_{cat}')

    # Vertical global-action stack, far right, above the detail bar.
    lines += [
        f'frame   x={gx} y={gy} w={gw} h={gh} title="KIT"',
        f'button  cx={gcx} cy={gy + 80}  label="GENERATE ALL" key=generate',
        f'button  cx={gcx} cy={gy + 180} label="CLEAR ALL" key=clear_all',
        f'button  cx={gcx} cy={gy + 280} label="NORMALISE" key=normalize',
        f'button  cx={gcx} cy={gy + 380} label="EXPORT KIT" key=export',
    ]

    # Full-width detail bar along the bottom. Gain knob sits directly
    # under the pad stepper (not beside the readout) so the sample-name
    # readout gets the freed width instead - long sample filenames were
    # the thing most likely to truncate on this whole page. LOCK/CLEAR/
    # REROLL share GAIN's horizontal centreline, per feedback on an
    # earlier draft that had them lower.
    nav_cx = dbx + 130
    stepper_cy = dby + 55
    knob_cy = dby + 145
    row2_cy = knob_cy
    lines += [
        f'frame   x={dbx} y={dby} w={dbw} h={dbh} title="PAD DETAIL"',
        f'stepper cx={nav_cx} cy={stepper_cy} w=220 h=44 label="" key=detail_pad_sel '
        f'get=detail_pad_name idx=detail_pad_sel count=detail_pad_count min=0 max=15 numbered=1',
        f'knob    cx={nav_cx} cy={knob_cy} r=35 label="GAIN" key=detail_gain min=0 max=2 pct=50',
        f'readout cx={dbx + 640} cy={stepper_cy} w=700 h=44 label="" get=detail_sample_info',
        # Width checked, not guessed: padded label = 208px wide, centered
        # at dbx+1120 spans 1016-1224, clear of the bar's right edge at
        # dbx+dbw=1260 (an earlier cx=dbx+1140 overflowed it by 4px).
        f'button  cx={dbx + 1120} cy={stepper_cy} label="   PLAY   " key=detail_play color={ACCENT_HEX}',
        f'toggle  cx={dbx + 350} cy={row2_cy} label="LOCK" key=detail_lock',
        f'button  cx={dbx + 650} cy={row2_cy} label="CLEAR" key=detail_clear',
        f'button  cx={dbx + 950} cy={row2_cy} label="REROLL" key=detail_reroll',
    ]

    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    import sys
    out = HEADER + '\n' + pads_grid_tab() + '\n' + detail_tab()
    dest = sys.argv[1] if len(sys.argv) > 1 else '/dev/stdout'
    with open(dest, 'w') as f:
        f.write(out)
    print(f'wrote {dest}', file=sys.stderr)
