#!/usr/bin/env python3
# Generates addon/shadow_page.conf's pad tabs programmatically - readout
# widgets take cx/cy (center point), not x/y (top-left), confirmed against
# force-shadow/src/force_shadow.c's real parser (frame/list use x/y;
# everything else uses cx/cy). Doing this by hand for 16 pads is exactly
# how the first draft got it wrong.

HEADER = '''# ForceKitBuilder — shadow-GUI page (v1: core loop only — generate,
# preview/lock, export). See DESIGN.md's "v2 scoping" section for the
# original control-key table/rationale, and "v2 refinements" /
# "Per-pad control redesign" for what changed since.
#
# page=8, not 1-7: only seven SHIFT+SCENE-N combos physically exist, and
# on the real device all seven were already taken (DX7, JV-880, Maze
# Voice, Maze Seq, Acid, Euclidier, plus force-shadow's own launcher at
# slot 7). Kit Builder is exactly the "low-frequency tool" case
# docs/adding-a-page.md's "Add-on launcher (tool add-ons)" section
# describes - page 8+ isn't combo-bound, it's reached via the launcher
# page (SHIFT+SCENE-7) instead. Confirmed live 2026-09-21: page=1
# silently lost the slot to ForceDX7 (already there first).
#
# Colour scheme: an approximation of the Akai Force's own OS look (dark
# charcoal chassis, cyan selection/accent, neutral grey buttons) rather
# than force-acid's td3 yellow/red - there's no captured reference screen-
# shot or verified hex values for the real Force OS in this repo family
# yet, so treat these exact values as a starting point to refine once
# compared side-by-side with the real hardware, not as confirmed-correct.
# Keeps style=td3's proven widget shapes (rounded frames, pill buttons)
# and only overrides the theme_* colour values.
#
# Layout: four tabs - PADS 1-8, PADS 9-16, GLOBAL, POOL ASSIGN. Each of
# the 16 pads carries its own LOCK/REROLL/CLEAR/PLAY controls directly
# (no more shared "selected pad" side panel + a 4x4 tap-to-select grid) -
# see DESIGN.md for why this needed splitting across two pad tabs: 16
# pads x (frame + readout + toggle + 3 buttons) = 96 widgets, over the
# format's 64-widgets-per-tab cap; 8 pads/tab x 6 widgets = 48, well
# under it, and leaves room to grow. This also delivers "bigger pads" -
# each pad now gets a full ~610x150 cell instead of a ~140px grid tile,
# room for the complete sample name instead of a truncated one. POOL
# ASSIGN is its own tab since 16 pads x 23 categories of individual
# toggles is nowhere near fitting alongside anything else - see
# DESIGN.md's "Pool assignment page" section for the full design.
#
# IMPORTANT widget coordinate rule (confirmed against
# force-shadow/src/force_shadow.c's real conf parser, not just the
# preview tool): frame and list take x=/y= (top-left corner). Every
# other widget kind - readout, toggle, button, knob, stepper, enum_h/v -
# takes cx=/cy= (CENTER point). Mixing these up (an earlier draft of
# this file used x=/y= on readout widgets) doesn't error, it just
# silently draws at/near (0,0) - caught by rendering with
# force-shadow/tools/render_conf_preview before deploying, not by
# inspection.
#
# Generated by tools/gen_shadow_page.py (force-kit-builder repo) - edit
# that script and regenerate rather than hand-editing the 16 near-
# identical pad blocks below.
page=8
ctrl_sock=/tmp/kitbuilder_ctrl.sock
display_name="KIT BUILDER"

style=td3
theme_bg=1a1a1a
theme_panel=1a1a1a
theme_line=2e2e2e
theme_ink=f2f2f2
theme_ink_dim=aaaaaa
theme_ink_faint=666666
theme_accent=ff8f00
theme_accent_hi=ffb74d
theme_knob_face=2a2a2a
theme_knob_ring=000000
theme_bar=2a2a2a
theme_seg_active=ff8f00
theme_seg_inactive=2a2a2a
theme_seg_active_tx=000000
theme_btn_text=ffffff
theme_well=000000
theme_knob_off=444444
theme_tab_on=2a2a2a
theme_lcd=000000
theme_box=202020
theme_btn_bg=3a3a3c
theme_chrome_ink=ffffff
theme_go_on=00e676
theme_go_off=616161
theme_tabs=1a1a1a
'''

# Same hex as theme_accent below - button `color=` overrides a single
# button's background (confirmed supported by both the preview tool and
# the real force_shadow.c parser, not just one of them), used here so
# PLAY stands out from the grey REROLL/CLEAR buttons without a second
# theme. See force-shadow/docs/adding-a-page.md's button syntax.
ACCENT_HEX = 'ff8f00'

CELL_W, CELL_H = 610, 150
COL_X = [20, 650]
ROW_Y = [82, 244, 406, 568]

# Status readout lives in the top bar (cy=36, inside TOPBAR_H's 72px),
# repeated on every tab - same pattern force-dx7/addon/shadow_page.conf
# uses for its bank-name readout (cy=36 on every one of its tabs; each
# tab redraws its own chrome, so a top-bar widget has to be repeated per
# tab, not declared once globally). Positioned right of the "KIT BUILDER"
# title (which ends well before x=420 at the title's scale=3) rather than
# where an engine on/off pill would go - we have no engine_process_name
# block, so on the real device (not just this preview tool, which always
# draws its own placeholder pill) that whole area is free.
TOPBAR_STATUS = 'readout cx=840 cy=36 w=780 h=48 label="" get=status'


def pad_cell(pad_num, pad_index, x, y):
    ro_cx = x + 14 + 582 // 2
    ro_cy = y + 30 + 50 // 2
    # Four controls now (was three) - LOCK/REROLL/CLEAR/PLAY split evenly
    # across the cell's ~582px interior. Checked by rendering, not just
    # computed - see gen_shadow_page.py's own history for why that matters
    # (an earlier all-16-pads layout got button-pill overlap wrong by
    # eyeballing the spacing instead).
    lock_cx, reroll_cx, clear_cx, play_cx = x + 90, x + 230, x + 370, x + 510
    ctrl_cy = y + 115
    lines = [
        f'frame   x={x}  y={y} w={CELL_W} h={CELL_H} title="PAD {pad_num}"',
        f'readout cx={ro_cx} cy={ro_cy} w=582 h=50 label="" get=pad_info_{pad_index}',
        f'toggle  cx={lock_cx} cy={ctrl_cy} label="LOCK" key=pad_lock_{pad_index}',
        f'button  cx={reroll_cx} cy={ctrl_cy} label="REROLL" key=reroll_pad_{pad_index}',
        f'button  cx={clear_cx} cy={ctrl_cy} label="CLEAR" key=clear_pad_{pad_index}',
        f'button  cx={play_cx} cy={ctrl_cy} label="PLAY" key=play_pad_{pad_index} color={ACCENT_HEX}',
    ]
    return '\n'.join(lines)


def pads_tab(name, start_pad_num):
    out = [f'[tab {name}]', TOPBAR_STATUS, '']
    for row in range(4):
        for col in range(2):
            pad_num = start_pad_num + row * 2 + col
            pad_index = pad_num - 1
            x, y = COL_X[col], ROW_Y[row]
            out.append(pad_cell(pad_num, pad_index, x, y))
            out.append('')
    return '\n'.join(out).rstrip() + '\n'


# ---- alternate layout: all 16 pads on one tab, no per-pad frame -----------
# readout + toggle + 2 buttons, x16 = 64 widgets - exactly the format's
# per-tab cap, zero widgets left over for a frame/title per pad (that's
# what padInfoText()'s own pad-number prefix is for instead - see
# daemon.mjs). GLOBAL actions still need their own separate tab; this
# only consolidates the 16 pads themselves down from two tabs to one.
ALL16_COLS = 4
ALL16_ROWS = 4
ALL16_CELL_W, ALL16_CELL_H = 295, 150
ALL16_GAP_X, ALL16_GAP_Y = 14, 10
ALL16_X0, ALL16_Y0 = 20, 85


def pad_cell_noframe(pad_index, x, y):
    ro_cx = x + ALL16_CELL_W // 2
    ro_cy = y + 30
    lock_cx = x + 50
    reroll_cx = x + ALL16_CELL_W // 2
    clear_cx = x + ALL16_CELL_W - 50
    ctrl_cy = y + 100
    lines = [
        f'readout cx={ro_cx} cy={ro_cy} w=275 h=40 label="" get=pad_info_{pad_index}',
        f'toggle  cx={lock_cx} cy={ctrl_cy} label="LOCK" key=pad_lock_{pad_index}',
        f'button  cx={reroll_cx} cy={ctrl_cy} label="REROLL" key=reroll_pad_{pad_index}',
        f'button  cx={clear_cx} cy={ctrl_cy} label="CLEAR" key=clear_pad_{pad_index}',
    ]
    return '\n'.join(lines)


def pads_tab_all16():
    # NOTE: adding TOPBAR_STATUS here pushes this tab to 65 widgets, one
    # over the 64 cap (16 pads x 4 widgets already used the whole budget -
    # see the module comment above). Left in for documentation/comparison
    # purposes only (this layout was already explored and rejected, see
    # DESIGN.md) - would need to drop one more widget to actually use it
    # with a top-bar status readout too.
    out = ['[tab PADS]', TOPBAR_STATUS, '']
    for row in range(ALL16_ROWS):
        for col in range(ALL16_COLS):
            pad_index = row * ALL16_COLS + col
            x = ALL16_X0 + col * (ALL16_CELL_W + ALL16_GAP_X)
            y = ALL16_Y0 + row * (ALL16_CELL_H + ALL16_GAP_Y)
            out.append(pad_cell_noframe(pad_index, x, y))
            out.append('')
    return '\n'.join(out).rstrip() + '\n'


def global_tab():
    # Status now lives in the top bar (TOPBAR_STATUS, repeated on every
    # tab including this one) rather than a big box at the bottom of just
    # this tab - frees this space up, so the four action buttons get more
    # room to breathe instead of being packed into the top half only.
    frame_x, frame_y, frame_w, frame_h = 200, 100, 880, 620
    cx = frame_x + frame_w // 2
    btn_ys = [220, 360, 500, 640]
    lines = [
        '[tab GLOBAL]',
        TOPBAR_STATUS,
        f'frame   x={frame_x} y={frame_y}  w={frame_w} h={frame_h} title="KIT ACTIONS"',
        f'button  cx={cx} cy={btn_ys[0]} label="GENERATE ALL" key=generate',
        f'button  cx={cx} cy={btn_ys[1]} label="CLEAR ALL" key=clear_all',
        f'button  cx={cx} cy={btn_ys[2]} label="NORMALISE" key=normalize',
        f'button  cx={cx} cy={btn_ys[3]} label="EXPORT KIT" key=export',
    ]
    return '\n'.join(lines) + '\n'


# ---- POOL ASSIGN tab: which categories each pad draws from ---------------
# core/sample_index.mjs's ROLE_ORDER, hardcoded here rather than read live -
# this script has no Node runtime to import it with. Keep in sync by hand;
# a mismatch wouldn't error, it would just make one category untoggleable
# from the shadow page (same class of silent-drift risk shadow-gui.md
# warns about for engine/web/shadow param triples generally).
CATEGORIES = [
    ('kick', 'KICK'), ('snare', 'SNARE'), ('rim', 'RIM'), ('clap', 'CLAP'),
    ('hat', 'HAT'), ('closed_hat', 'CLOSED HAT'), ('open_hat', 'OPEN HAT'),
    ('tom', 'TOM'), ('conga', 'CONGA'), ('percussion', 'PERC'),
    ('crash', 'CRASH'), ('ride', 'RIDE'), ('cymbal', 'CYMBAL'), ('fx', 'FX'),
    ('glitch', 'GLITCH'), ('vox', 'VOX'), ('bass', 'BASS'), ('synth', 'SYNTH'),
    ('stab', 'STAB'), ('chord', 'CHORD'), ('lead', 'LEAD'), ('pad', 'PAD'),
    ('other', 'OTHER'),
]

POOL_FRAME1 = (20, 82, 1240, 260)     # SELECT PAD
POOL_FRAME2 = (20, 360, 1240, 360)    # CATEGORIES
POOL_CAT_COLS, POOL_CAT_ROWS = 6, 4


def pool_tab():
    f1x, f1y, f1w, f1h = POOL_FRAME1
    f2x, f2y, f2w, f2h = POOL_FRAME2

    # frame_box() (both the preview tool and the real force_shadow.c) draws
    # the frame's own title at y+14 and a divider rule at y+38 - anything
    # placed above that divider collides with the title text. First draft
    # put the readout/RESET row at y+32, squarely on top of "SELECT PAD" -
    # caught by rendering (a stray "S" was all that showed), not by the
    # numbers. Everything else here starts below y+38.
    row1_cy = f1y + 55
    list_cx0, list_cy0 = f1x + 16, f1y + 90
    list_w, list_h = f1w - 32, f1h - 106
    list_th = (list_h - 10) // 2   # 2 rows, gap=10

    lines = [
        '[tab POOL ASSIGN]',
        f'frame   x={f1x} y={f1y} w={f1w} h={f1h} title="SELECT PAD"',
        f'readout cx={f1x + 220} cy={row1_cy} w=360 h=32 label="" get=pool_editing_label',
        f'button  cx={f1x + f1w - 120} cy={row1_cy} label="RESET" key=pool_reset',
        f'list    x={list_cx0} y={list_cy0} w={list_w} h={list_h} key=pool_pad_sel items=pool_pads sel=pool_pad_sel cols=8 rows=2 th={list_th} gap=10 jump=0 colmajor=0 numbered=1 scale=1.5',
        f'frame   x={f2x} y={f2y} w={f2w} h={f2h} title="CATEGORIES - TAP TO TOGGLE"',
    ]

    interior_x0, interior_x1 = f2x + 16, f2x + f2w - 16
    interior_y0, interior_y1 = f2y + 40, f2y + f2h - 16
    col_step = (interior_x1 - interior_x0) / POOL_CAT_COLS
    row_step = (interior_y1 - interior_y0) / POOL_CAT_ROWS

    for i, (cat, label) in enumerate(CATEGORIES):
        col = i % POOL_CAT_COLS
        row = i // POOL_CAT_COLS
        cx = int(interior_x0 + col_step * col + col_step / 2)
        cy = int(interior_y0 + row_step * row + row_step / 2)
        lines.append(f'toggle  cx={cx} cy={cy} label="{label}" key=pool_cat_{cat}')

    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    import sys
    args = sys.argv[1:]
    one_page = '--one-page' in args
    args = [a for a in args if a != '--one-page']
    if one_page:
        # Comparison layout - all 16 pads on one tab (no per-pad frame,
        # exactly 64 widgets), GLOBAL still separate. Not the committed
        # default; generate explicitly to compare against the 2-tab layout.
        out = HEADER + '\n' + pads_tab_all16() + '\n' + global_tab() + '\n' + pool_tab()
    else:
        out = (HEADER + '\n' + pads_tab('PADS 1-8', 1) + '\n' + pads_tab('PADS 9-16', 9)
               + '\n' + global_tab() + '\n' + pool_tab())
    dest = args[0] if args else '/dev/stdout'
    with open(dest, 'w') as f:
        f.write(out)
    print(f'wrote {dest}', file=sys.stderr)
