#!/usr/bin/env python3
# Generates addon/shadow_page.conf's pad tabs programmatically - readout
# widgets take cx/cy (center point), not x/y (top-left), confirmed against
# force-shadow/src/force_shadow.c's real parser (frame/list use x/y;
# everything else uses cx/cy). Doing this by hand for 16 pads is exactly
# how the first draft got it wrong.

HEADER = '''# ForceKitBuilder — shadow-GUI page (v1: core loop only — generate,
# preview/lock, export). See DESIGN.md's "v2 scoping" section for the
# original control-key table/rationale, and "v2 refinements" /
# "Per-pad control redesign" for what changed since.
#
# page=8, not 1-7: only seven SHIFT+SCENE-N combos physically exist, and
# on the real device all seven were already taken (DX7, JV-880, Maze
# Voice, Maze Seq, Acid, Euclidier, plus force-shadow's own launcher at
# slot 7). Kit Builder is exactly the "low-frequency tool" case
# docs/adding-a-page.md's "Add-on launcher (tool add-ons)" section
# describes - page 8+ isn't combo-bound, it's reached via the launcher
# page (SHIFT+SCENE-7) instead. Confirmed live 2026-09-21: page=1
# silently lost the slot to ForceDX7 (already there first).
#
# Colour scheme: an approximation of the Akai Force's own OS look (dark
# charcoal chassis, cyan selection/accent, neutral grey buttons) rather
# than force-acid's td3 yellow/red - there's no captured reference screen-
# shot or verified hex values for the real Force OS in this repo family
# yet, so treat these exact values as a starting point to refine once
# compared side-by-side with the real hardware, not as confirmed-correct.
# Keeps style=td3's proven widget shapes (rounded frames, pill buttons)
# and only overrides the theme_* colour values.
#
# Layout: three tabs instead of one - PADS 1-8, PADS 9-16, GLOBAL. Each
# of the 16 pads now carries its own LOCK/REROLL/CLEAR controls directly
# (no more shared "selected pad" side panel + a 4x4 tap-to-select grid) -
# see DESIGN.md for why this needed splitting across two pad tabs: 16
# pads x (frame + readout + toggle + 2 buttons) = 80 widgets, over the
# format's 64-widgets-per-tab cap; 8 pads/tab x 5 widgets = 40, well
# under it, and leaves room to grow. This also delivers "bigger pads" -
# each pad now gets a full ~610x150 cell instead of a ~140px grid tile,
# room for the complete sample name instead of a truncated one.
#
# IMPORTANT widget coordinate rule (confirmed against
# force-shadow/src/force_shadow.c's real conf parser, not just the
# preview tool): frame and list take x=/y= (top-left corner). Every
# other widget kind - readout, toggle, button, knob, stepper, enum_h/v -
# takes cx=/cy= (CENTER point). Mixing these up (an earlier draft of
# this file used x=/y= on readout widgets) doesn't error, it just
# silently draws at/near (0,0) - caught by rendering with
# force-shadow/tools/render_conf_preview before deploying, not by
# inspection.
#
# Generated by tools/gen_shadow_page.py (force-kit-builder repo) - edit
# that script and regenerate rather than hand-editing the 16 near-
# identical pad blocks below.
page=8
ctrl_sock=/tmp/kitbuilder_ctrl.sock
display_name="KIT BUILDER"

style=td3
theme_bg=1a1a1a
theme_panel=1a1a1a
theme_line=2e2e2e
theme_ink=f2f2f2
theme_ink_dim=aaaaaa
theme_ink_faint=666666
theme_accent=ff8f00
theme_accent_hi=ffb74d
theme_knob_face=2a2a2a
theme_knob_ring=000000
theme_bar=2a2a2a
theme_seg_active=ff8f00
theme_seg_inactive=2a2a2a
theme_seg_active_tx=000000
theme_btn_text=ffffff
theme_well=000000
theme_knob_off=444444
theme_tab_on=2a2a2a
theme_lcd=000000
theme_box=202020
theme_btn_bg=3a3a3c
theme_chrome_ink=ffffff
theme_go_on=00e676
theme_go_off=616161
theme_tabs=1a1a1a
'''

CELL_W, CELL_H = 610, 150
COL_X = [20, 650]
ROW_Y = [82, 244, 406, 568]

# Status readout lives in the top bar (cy=36, inside TOPBAR_H's 72px),
# repeated on every tab - same pattern force-dx7/addon/shadow_page.conf
# uses for its bank-name readout (cy=36 on every one of its tabs; each
# tab redraws its own chrome, so a top-bar widget has to be repeated per
# tab, not declared once globally). Positioned right of the "KIT BUILDER"
# title (which ends well before x=420 at the title's scale=3) rather than
# where an engine on/off pill would go - we have no engine_process_name
# block, so on the real device (not just this preview tool, which always
# draws its own placeholder pill) that whole area is free.
TOPBAR_STATUS = 'readout cx=840 cy=36 w=780 h=48 label="" get=status'


def pad_cell(pad_num, pad_index, x, y):
    ro_cx = x + 14 + 582 // 2
    ro_cy = y + 30 + 50 // 2
    # Four controls now (was three) - LOCK/REROLL/CLEAR/PLAY split evenly
    # across the cell's ~582px interior. Checked by rendering, not just
    # computed - see gen_shadow_page.py's own history for why that matters
    # (an earlier all-16-pads layout got button-pill overlap wrong by
    # eyeballing the spacing instead).
    lock_cx, reroll_cx, clear_cx, play_cx = x + 90, x + 230, x + 370, x + 510
    ctrl_cy = y + 115
    lines = [
        f'frame   x={x}  y={y} w={CELL_W} h={CELL_H} title="PAD {pad_num}"',
        f'readout cx={ro_cx} cy={ro_cy} w=582 h=50 label="" get=pad_info_{pad_index}',
        f'toggle  cx={lock_cx} cy={ctrl_cy} label="LOCK" key=pad_lock_{pad_index}',
        f'button  cx={reroll_cx} cy={ctrl_cy} label="REROLL" key=reroll_pad_{pad_index}',
        f'button  cx={clear_cx} cy={ctrl_cy} label="CLEAR" key=clear_pad_{pad_index}',
        f'button  cx={play_cx} cy={ctrl_cy} label="PLAY" key=play_pad_{pad_index}',
    ]
    return '\n'.join(lines)


def pads_tab(name, start_pad_num):
    out = [f'[tab {name}]', TOPBAR_STATUS, '']
    for row in range(4):
        for col in range(2):
            pad_num = start_pad_num + row * 2 + col
            pad_index = pad_num - 1
            x, y = COL_X[col], ROW_Y[row]
            out.append(pad_cell(pad_num, pad_index, x, y))
            out.append('')
    return '\n'.join(out).rstrip() + '\n'


# ---- alternate layout: all 16 pads on one tab, no per-pad frame -----------
# readout + toggle + 2 buttons, x16 = 64 widgets - exactly the format's
# per-tab cap, zero widgets left over for a frame/title per pad (that's
# what padInfoText()'s own pad-number prefix is for instead - see
# daemon.mjs). GLOBAL actions still need their own separate tab; this
# only consolidates the 16 pads themselves down from two tabs to one.
ALL16_COLS = 4
ALL16_ROWS = 4
ALL16_CELL_W, ALL16_CELL_H = 295, 150
ALL16_GAP_X, ALL16_GAP_Y = 14, 10
ALL16_X0, ALL16_Y0 = 20, 85


def pad_cell_noframe(pad_index, x, y):
    ro_cx = x + ALL16_CELL_W // 2
    ro_cy = y + 30
    lock_cx = x + 50
    reroll_cx = x + ALL16_CELL_W // 2
    clear_cx = x + ALL16_CELL_W - 50
    ctrl_cy = y + 100
    lines = [
        f'readout cx={ro_cx} cy={ro_cy} w=275 h=40 label="" get=pad_info_{pad_index}',
        f'toggle  cx={lock_cx} cy={ctrl_cy} label="LOCK" key=pad_lock_{pad_index}',
        f'button  cx={reroll_cx} cy={ctrl_cy} label="REROLL" key=reroll_pad_{pad_index}',
        f'button  cx={clear_cx} cy={ctrl_cy} label="CLEAR" key=clear_pad_{pad_index}',
    ]
    return '\n'.join(lines)


def pads_tab_all16():
    # NOTE: adding TOPBAR_STATUS here pushes this tab to 65 widgets, one
    # over the 64 cap (16 pads x 4 widgets already used the whole budget -
    # see the module comment above). Left in for documentation/comparison
    # purposes only (this layout was already explored and rejected, see
    # DESIGN.md) - would need to drop one more widget to actually use it
    # with a top-bar status readout too.
    out = ['[tab PADS]', TOPBAR_STATUS, '']
    for row in range(ALL16_ROWS):
        for col in range(ALL16_COLS):
            pad_index = row * ALL16_COLS + col
            x = ALL16_X0 + col * (ALL16_CELL_W + ALL16_GAP_X)
            y = ALL16_Y0 + row * (ALL16_CELL_H + ALL16_GAP_Y)
            out.append(pad_cell_noframe(pad_index, x, y))
            out.append('')
    return '\n'.join(out).rstrip() + '\n'


def global_tab():
    # Status now lives in the top bar (TOPBAR_STATUS, repeated on every
    # tab including this one) rather than a big box at the bottom of just
    # this tab - frees this space up, so the four action buttons get more
    # room to breathe instead of being packed into the top half only.
    frame_x, frame_y, frame_w, frame_h = 200, 100, 880, 620
    cx = frame_x + frame_w // 2
    btn_ys = [220, 360, 500, 640]
    lines = [
        '[tab GLOBAL]',
        TOPBAR_STATUS,
        f'frame   x={frame_x} y={frame_y}  w={frame_w} h={frame_h} title="KIT ACTIONS"',
        f'button  cx={cx} cy={btn_ys[0]} label="GENERATE ALL" key=generate',
        f'button  cx={cx} cy={btn_ys[1]} label="CLEAR ALL" key=clear_all',
        f'button  cx={cx} cy={btn_ys[2]} label="NORMALISE" key=normalize',
        f'button  cx={cx} cy={btn_ys[3]} label="EXPORT KIT" key=export',
    ]
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    import sys
    args = sys.argv[1:]
    one_page = '--one-page' in args
    args = [a for a in args if a != '--one-page']
    if one_page:
        # Comparison layout - all 16 pads on one tab (no per-pad frame,
        # exactly 64 widgets), GLOBAL still separate. Not the committed
        # default; generate explicitly to compare against the 2-tab layout.
        out = HEADER + '\n' + pads_tab_all16() + '\n' + global_tab()
    else:
        out = HEADER + '\n' + pads_tab('PADS 1-8', 1) + '\n' + pads_tab('PADS 9-16', 9) + '\n' + global_tab()
    dest = args[0] if args else '/dev/stdout'
    with open(dest, 'w') as f:
        f.write(out)
    print(f'wrote {dest}', file=sys.stderr)
